//
// Created by Administrator on 2026/6/23.
//

#ifndef NEU_2024_DATASTRUCTURE_TINYDELIVERY_CONTRACTSYSTEM_H
#define NEU_2024_DATASTRUCTURE_TINYDELIVERY_CONTRACTSYSTEM_H


class ContractSystem {
};


#endif //NEU_2024_DATASTRUCTURE_TINYDELIVERY_CONTRACTSYSTEM_H
