//
// Created by Administrator on 2026/6/23.
//

#ifndef NEU_2024_DATASTRUCTURE_TINYDELIVERY_DISPATCHSYSTEM_H
#define NEU_2024_DATASTRUCTURE_TINYDELIVERY_DISPATCHSYSTEM_H


class DispatchSystem {
};


#endif //NEU_2024_DATASTRUCTURE_TINYDELIVERY_DISPATCHSYSTEM_H
