//
// Created by Administrator on 2026/6/23.
//

#ifndef NEU_2024_DATASTRUCTURE_TINYDELIVERY_UPGRADESYSTEM_H
#define NEU_2024_DATASTRUCTURE_TINYDELIVERY_UPGRADESYSTEM_H


class UpgradeSystem {
};


#endif //NEU_2024_DATASTRUCTURE_TINYDELIVERY_UPGRADESYSTEM_H
