//
// Created by Administrator on 2026/6/23.
//

#ifndef NEU_2024_DATASTRUCTURE_TINYDELIVERY_WAREHOUSESYSTEM_H
#define NEU_2024_DATASTRUCTURE_TINYDELIVERY_WAREHOUSESYSTEM_H


class WarehouseSystem {
};


#endif //NEU_2024_DATASTRUCTURE_TINYDELIVERY_WAREHOUSESYSTEM_H
