//
// Created by Administrator on 2026/6/23.
//

#ifndef NEU_2024_DATASTRUCTURE_TINYDELIVERY_LOGGER_H
#define NEU_2024_DATASTRUCTURE_TINYDELIVERY_LOGGER_H


class log_ {
};


#endif //NEU_2024_DATASTRUCTURE_TINYDELIVERY_LOGGER_H
