//
// Created by Administrator on 2026/6/23.
//

#ifndef NEU_2024_DATASTRUCTURE_TINYDELIVERY_RANDOMGENERATOR_H
#define NEU_2024_DATASTRUCTURE_TINYDELIVERY_RANDOMGENERATOR_H


class random_ {
};


#endif //NEU_2024_DATASTRUCTURE_TINYDELIVERY_RANDOMGENERATOR_H
