//
// Created by Administrator on 2026/6/23.
//

#ifndef NEU_2024_DATASTRUCTURE_TINYDELIVERY_TIMEMANAGER_H
#define NEU_2024_DATASTRUCTURE_TINYDELIVERY_TIMEMANAGER_H


class time_ {
};


#endif //NEU_2024_DATASTRUCTURE_TINYDELIVERY_TIMEMANAGER_H
