//
// Created by Administrator on 2026/6/23.
//

#ifndef NEU_2024_DATASTRUCTURE_TINYDELIVERY_DELIEVER_H
#define NEU_2024_DATASTRUCTURE_TINYDELIVERY_DELIEVER_H


class Deliever {
};


#endif //NEU_2024_DATASTRUCTURE_TINYDELIVERY_DELIEVER_H
