//
// Created by Administrator on 2026/6/23.
//

#ifndef NEU_2024_DATASTRUCTURE_TINYDELIVERY_MERCHANT_H
#define NEU_2024_DATASTRUCTURE_TINYDELIVERY_MERCHANT_H


class Merchant {
};


#endif //NEU_2024_DATASTRUCTURE_TINYDELIVERY_MERCHANT_H
