//
// Created by Administrator on 2026/6/23.
//

#ifndef NEU_2024_DATASTRUCTURE_TINYDELIVERY_VEHICLE_H
#define NEU_2024_DATASTRUCTURE_TINYDELIVERY_VEHICLE_H


class Vehicle {
};


#endif //NEU_2024_DATASTRUCTURE_TINYDELIVERY_VEHICLE_H
