//
// Created by Administrator on 2026/6/23.
//

#ifndef NEU_2024_DATASTRUCTURE_TINYDELIVERY_WAREHOUSE_H
#define NEU_2024_DATASTRUCTURE_TINYDELIVERY_WAREHOUSE_H


class Warehouse {
};


#endif //NEU_2024_DATASTRUCTURE_TINYDELIVERY_WAREHOUSE_H
