//
// Created by Administrator on 2026/6/23.
//

#ifndef NEU_2024_DATASTRUCTURE_TINYDELIVERY_MAINWINDOW_H
#define NEU_2024_DATASTRUCTURE_TINYDELIVERY_MAINWINDOW_H


class MainWindow {
};


#endif //NEU_2024_DATASTRUCTURE_TINYDELIVERY_MAINWINDOW_H
