//
// Created by Administrator on 2026/6/23.
//

#ifndef NEU_2024_DATASTRUCTURE_TINYDELIVERY_MAPWIDGET_H
#define NEU_2024_DATASTRUCTURE_TINYDELIVERY_MAPWIDGET_H


class MapWidget {
};


#endif //NEU_2024_DATASTRUCTURE_TINYDELIVERY_MAPWIDGET_H
