//
// Created by Administrator on 2026/6/23.
//

#ifndef NEU_2024_DATASTRUCTURE_TINYDELIVERY_PATHFINDER_H
#define NEU_2024_DATASTRUCTURE_TINYDELIVERY_PATHFINDER_H


class PathFinder {
};


#endif //NEU_2024_DATASTRUCTURE_TINYDELIVERY_PATHFINDER_H
