//
// Created by Administrator on 2026/6/23.
//

#ifndef NEU_2024_DATASTRUCTURE_TINYDELIVERY_GAMESTATE_H
#define NEU_2024_DATASTRUCTURE_TINYDELIVERY_GAMESTATE_H


class GameState {
};


#endif //NEU_2024_DATASTRUCTURE_TINYDELIVERY_GAMESTATE_H
