//
// Created by Administrator on 2026/6/23.
//

#ifndef NEU_2024_DATASTRUCTURE_TINYDELIVERY_CONTROLPANEL_H
#define NEU_2024_DATASTRUCTURE_TINYDELIVERY_CONTROLPANEL_H


class ControlPanel {
};


#endif //NEU_2024_DATASTRUCTURE_TINYDELIVERY_CONTROLPANEL_H
