//
// Created by Administrator on 2026/6/23.
//

#ifndef NEU_2024_DATASTRUCTURE_TINYDELIVERY_CUSTOMERPANEL_H
#define NEU_2024_DATASTRUCTURE_TINYDELIVERY_CUSTOMERPANEL_H


class CustomerPanel {
};


#endif //NEU_2024_DATASTRUCTURE_TINYDELIVERY_CUSTOMERPANEL_H
