//
// Created by Administrator on 2026/6/23.
//

#ifndef NEU_2024_DATASTRUCTURE_TINYDELIVERY_DASHBOARDPANEL_H
#define NEU_2024_DATASTRUCTURE_TINYDELIVERY_DASHBOARDPANEL_H


class DashboardPanel {
};


#endif //NEU_2024_DATASTRUCTURE_TINYDELIVERY_DASHBOARDPANEL_H
