//
// Created by Administrator on 2026/6/23.
//

#ifndef NEU_2024_DATASTRUCTURE_TINYDELIVERY_DELIVERPANEL_H
#define NEU_2024_DATASTRUCTURE_TINYDELIVERY_DELIVERPANEL_H


class DeliverPanel {
};


#endif //NEU_2024_DATASTRUCTURE_TINYDELIVERY_DELIVERPANEL_H
